use crate::api::types::{
    Agent, AgentList, ArtifactList, Conversation, DeleteResponse, FollowupRequest,
    FollowupResponse, GetArtifactResponse, LaunchRequest, MeResponse, ModelList, RepoList,
    StopResponse,
};
use crate::error::Result;
use todoku::{BearerToken, HttpClient};

/// HTTP client for the Cursor Cloud Agents API.
///
/// Wraps `todoku::HttpClient` with Bearer auth per the `OpenAPI` spec.
/// All endpoints are prefixed with `/v0`.
#[derive(Clone)]
pub struct CursorCloudClient {
    http: HttpClient,
}

impl std::fmt::Debug for CursorCloudClient {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CursorCloudClient").finish()
    }
}

impl CursorCloudClient {
    /// Create a new client with Bearer token authentication.
    pub fn new(base_url: &str, api_key: &str) -> Result<Self> {
        let http = HttpClient::builder()
            .base_url(base_url)
            .auth(BearerToken::new(api_key))
            .user_agent("pleme-io/kurage 0.1.0")
            .build()?;

        Ok(Self { http })
    }

    // ── Public API methods ──────────────────────────────────────────────────

    /// POST /v0/agents — Launch a new cloud agent.
    pub async fn launch(&self, req: &LaunchRequest) -> Result<Agent> {
        Ok(self.http.post("/v0/agents", req).await?)
    }

    /// GET /v0/agents — List agents with optional pagination and PR filter.
    pub async fn list(
        &self,
        limit: u32,
        cursor: Option<&str>,
        pr_url: Option<&str>,
    ) -> Result<AgentList> {
        let path = build_list_path(limit, cursor, pr_url);
        Ok(self.http.get(&path).await?)
    }

    /// GET /v0/agents/{id} — Get agent status.
    pub async fn status(&self, id: &str) -> Result<Agent> {
        Ok(self.http.get(&format!("/v0/agents/{id}")).await?)
    }

    /// GET /v0/agents/{id}/conversation — Get agent conversation logs.
    pub async fn logs(&self, id: &str) -> Result<Conversation> {
        Ok(self.http.get(&format!("/v0/agents/{id}/conversation")).await?)
    }

    /// POST /v0/agents/{id}/stop — Stop a running agent.
    pub async fn stop(&self, id: &str) -> Result<StopResponse> {
        Ok(self.http.post(&format!("/v0/agents/{id}/stop"), &serde_json::Value::Null).await?)
    }

    /// POST /v0/agents/{id}/followup — Add a followup instruction.
    pub async fn followup(&self, id: &str, req: &FollowupRequest) -> Result<FollowupResponse> {
        Ok(self.http.post(&format!("/v0/agents/{id}/followup"), req).await?)
    }

    /// DELETE /v0/agents/{id} — Delete an agent permanently.
    pub async fn delete_agent(&self, id: &str) -> Result<DeleteResponse> {
        Ok(self.http.delete(&format!("/v0/agents/{id}")).await?)
    }

    /// GET /v0/agents/{id}/artifacts — List artifacts generated by an agent.
    pub async fn artifacts(&self, id: &str) -> Result<ArtifactList> {
        Ok(self.http.get(&format!("/v0/agents/{id}/artifacts")).await?)
    }

    /// GET /v0/agents/{id}/artifacts/download?path={path} — Get a presigned download URL.
    pub async fn download_artifact(
        &self,
        id: &str,
        path: &str,
    ) -> Result<GetArtifactResponse> {
        let url = build_download_path(id, path);
        Ok(self.http.get(&url).await?)
    }

    /// GET /v0/models — List available models.
    pub async fn models(&self) -> Result<ModelList> {
        Ok(self.http.get("/v0/models").await?)
    }

    /// GET /v0/repositories — List accessible GitHub repositories.
    pub async fn repos(&self) -> Result<RepoList> {
        Ok(self.http.get("/v0/repositories").await?)
    }

    /// GET /v0/me — Get API key information.
    pub async fn me(&self) -> Result<MeResponse> {
        Ok(self.http.get("/v0/me").await?)
    }
}

/// Build the query-string path for the list-agents endpoint.
fn build_list_path(limit: u32, cursor: Option<&str>, pr_url: Option<&str>) -> String {
    use std::fmt::Write;
    let mut path = format!("/v0/agents?limit={limit}");
    if let Some(c) = cursor {
        let _ = write!(path, "&cursor={}", urlencoding::encode(c));
    }
    if let Some(pr) = pr_url {
        let _ = write!(path, "&prUrl={}", urlencoding::encode(pr));
    }
    path
}

/// Build the query-string path for the download-artifact endpoint.
fn build_download_path(id: &str, artifact_path: &str) -> String {
    format!(
        "/v0/agents/{id}/artifacts/download?path={}",
        urlencoding::encode(artifact_path)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_list_path_limit_only() {
        let path = build_list_path(20, None, None);
        assert_eq!(path, "/v0/agents?limit=20");
    }

    #[test]
    fn build_list_path_with_cursor() {
        let path = build_list_path(10, Some("abc123"), None);
        assert_eq!(path, "/v0/agents?limit=10&cursor=abc123");
    }

    #[test]
    fn build_list_path_with_pr_url() {
        let path = build_list_path(5, None, Some("https://github.com/org/repo/pull/1"));
        assert!(path.starts_with("/v0/agents?limit=5&prUrl="));
        assert!(path.contains("https%3A%2F%2Fgithub.com"));
    }

    #[test]
    fn build_list_path_with_all_params() {
        let path = build_list_path(
            50,
            Some("cur_xyz"),
            Some("https://github.com/org/repo/pull/42"),
        );
        assert!(path.starts_with("/v0/agents?limit=50"));
        assert!(path.contains("&cursor=cur_xyz"));
        assert!(path.contains("&prUrl="));
    }

    #[test]
    fn build_list_path_cursor_url_encoded() {
        let path = build_list_path(20, Some("a b&c=d"), None);
        assert!(path.contains("cursor=a%20b%26c%3Dd"));
    }

    #[test]
    fn build_download_path_basic() {
        let path = build_download_path("bc_123", "/opt/cursor/artifacts/file.txt");
        assert_eq!(
            path,
            "/v0/agents/bc_123/artifacts/download?path=%2Fopt%2Fcursor%2Fartifacts%2Ffile.txt"
        );
    }

    #[test]
    fn build_download_path_special_chars() {
        let path = build_download_path("bc_1", "/path/with spaces/file (1).txt");
        assert!(path.contains("path="));
        assert!(path.contains("%20"));
    }

    #[test]
    fn client_debug_impl() {
        let debug = format!("{:?}", CursorCloudClient::new("https://example.com", "key").unwrap());
        assert!(debug.contains("CursorCloudClient"));
    }
}
