use crate::api::types::{
    Agent, AgentList, ArtifactList, Conversation, DeleteResponse, FollowupRequest,
    FollowupResponse, GetArtifactResponse, LaunchRequest, MeResponse, ModelList, RepoList,
    StopResponse,
};
use crate::error::{KurageError, Result};

/// HTTP client for the Cursor Cloud Agents API.
///
/// Auth uses Bearer token per the OpenAPI spec (`bearerAuth`, scheme: bearer).
/// All endpoints are prefixed with `/v0`.
#[derive(Debug, Clone)]
pub struct CursorCloudClient {
    inner: reqwest::Client,
    base_url: String,
    api_key: String,
}

impl CursorCloudClient {
    /// Create a new client.
    pub fn new(base_url: &str, api_key: &str) -> Result<Self> {
        let inner = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(60))
            .user_agent("pleme-io/kurage 0.1.0")
            .build()
            .map_err(KurageError::Request)?;

        Ok(Self {
            inner,
            base_url: base_url.trim_end_matches('/').to_string(),
            api_key: api_key.to_string(),
        })
    }

    fn url(&self, path: &str) -> String {
        format!("{}/{}", self.base_url, path.trim_start_matches('/'))
    }

    async fn get<T: serde::de::DeserializeOwned>(&self, path: &str) -> Result<T> {
        let resp = self
            .inner
            .get(&self.url(path))
            .bearer_auth(&self.api_key)
            .send()
            .await
            .map_err(KurageError::Request)?;
        Self::handle_response(resp).await
    }

    async fn post<B: serde::Serialize, T: serde::de::DeserializeOwned>(
        &self,
        path: &str,
        body: &B,
    ) -> Result<T> {
        let resp = self
            .inner
            .post(&self.url(path))
            .bearer_auth(&self.api_key)
            .json(body)
            .send()
            .await
            .map_err(KurageError::Request)?;
        Self::handle_response(resp).await
    }

    async fn post_empty<T: serde::de::DeserializeOwned>(&self, path: &str) -> Result<T> {
        let resp = self
            .inner
            .post(&self.url(path))
            .bearer_auth(&self.api_key)
            .send()
            .await
            .map_err(KurageError::Request)?;
        Self::handle_response(resp).await
    }

    async fn delete<T: serde::de::DeserializeOwned>(&self, path: &str) -> Result<T> {
        let resp = self
            .inner
            .delete(&self.url(path))
            .bearer_auth(&self.api_key)
            .send()
            .await
            .map_err(KurageError::Request)?;
        Self::handle_response(resp).await
    }

    async fn handle_response<T: serde::de::DeserializeOwned>(
        resp: reqwest::Response,
    ) -> Result<T> {
        let status = resp.status().as_u16();
        if !resp.status().is_success() {
            let body = resp.text().await.unwrap_or_default();
            return Err(KurageError::Api { status, body });
        }
        let text = resp.text().await.map_err(KurageError::Request)?;
        serde_json::from_str(&text).map_err(KurageError::Json)
    }

    // ── Public API methods ──────────────────────────────────────────────────

    /// POST /v0/agents — Launch a new cloud agent.
    pub async fn launch(&self, req: &LaunchRequest) -> Result<Agent> {
        self.post("/v0/agents", req).await
    }

    /// GET /v0/agents — List agents with optional pagination and PR filter.
    pub async fn list(
        &self,
        limit: u32,
        cursor: Option<&str>,
        pr_url: Option<&str>,
    ) -> Result<AgentList> {
        let mut path = format!("/v0/agents?limit={limit}");
        if let Some(c) = cursor {
            path.push_str(&format!("&cursor={}", urlencoding::encode(c)));
        }
        if let Some(pr) = pr_url {
            path.push_str(&format!("&prUrl={}", urlencoding::encode(pr)));
        }
        self.get(&path).await
    }

    /// GET /v0/agents/{id} — Get agent status.
    pub async fn status(&self, id: &str) -> Result<Agent> {
        self.get(&format!("/v0/agents/{id}")).await
    }

    /// GET /v0/agents/{id}/conversation — Get agent conversation logs.
    pub async fn logs(&self, id: &str) -> Result<Conversation> {
        self.get(&format!("/v0/agents/{id}/conversation")).await
    }

    /// POST /v0/agents/{id}/stop — Stop a running agent.
    pub async fn stop(&self, id: &str) -> Result<StopResponse> {
        self.post_empty(&format!("/v0/agents/{id}/stop")).await
    }

    /// POST /v0/agents/{id}/followup — Add a followup instruction.
    pub async fn followup(&self, id: &str, req: &FollowupRequest) -> Result<FollowupResponse> {
        self.post(&format!("/v0/agents/{id}/followup"), req).await
    }

    /// DELETE /v0/agents/{id} — Delete an agent permanently.
    pub async fn delete_agent(&self, id: &str) -> Result<DeleteResponse> {
        self.delete(&format!("/v0/agents/{id}")).await
    }

    /// GET /v0/agents/{id}/artifacts — List artifacts generated by an agent.
    pub async fn artifacts(&self, id: &str) -> Result<ArtifactList> {
        self.get(&format!("/v0/agents/{id}/artifacts")).await
    }

    /// GET /v0/agents/{id}/artifacts/download?path={path} — Get a presigned download URL.
    pub async fn download_artifact(
        &self,
        id: &str,
        path: &str,
    ) -> Result<GetArtifactResponse> {
        self.get(&format!(
            "/v0/agents/{id}/artifacts/download?path={}",
            urlencoding::encode(path)
        ))
        .await
    }

    /// GET /v0/models — List available models.
    pub async fn models(&self) -> Result<ModelList> {
        self.get("/v0/models").await
    }

    /// GET /v0/repositories — List accessible GitHub repositories.
    pub async fn repos(&self) -> Result<RepoList> {
        self.get("/v0/repositories").await
    }

    /// GET /v0/me — Get API key information.
    pub async fn me(&self) -> Result<MeResponse> {
        self.get("/v0/me").await
    }
}
