use crate::api::types::{
    Agent, AgentList, ArtifactList, Conversation, DeleteResponse, FollowupRequest,
    FollowupResponse, GetArtifactResponse, LaunchRequest, MeResponse, ModelList, RepoList,
    StopResponse,
};
use crate::error::Result;
use todoku::{BearerToken, HttpClient};

/// HTTP client for the Cursor Cloud Agents API.
///
/// Wraps `todoku::HttpClient` with Bearer auth per the OpenAPI spec.
/// All endpoints are prefixed with `/v0`.
#[derive(Clone)]
pub struct CursorCloudClient {
    http: HttpClient,
}

impl std::fmt::Debug for CursorCloudClient {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CursorCloudClient").finish()
    }
}

impl CursorCloudClient {
    /// Create a new client with Bearer token authentication.
    pub fn new(base_url: &str, api_key: &str) -> Result<Self> {
        let http = HttpClient::builder()
            .base_url(base_url)
            .auth(BearerToken::new(api_key))
            .user_agent("pleme-io/kurage 0.1.0")
            .build()?;

        Ok(Self { http })
    }

    // ── Public API methods ──────────────────────────────────────────────────

    /// POST /v0/agents — Launch a new cloud agent.
    pub async fn launch(&self, req: &LaunchRequest) -> Result<Agent> {
        Ok(self.http.post("/v0/agents", req).await?)
    }

    /// GET /v0/agents — List agents with optional pagination and PR filter.
    pub async fn list(
        &self,
        limit: u32,
        cursor: Option<&str>,
        pr_url: Option<&str>,
    ) -> Result<AgentList> {
        let mut path = format!("/v0/agents?limit={limit}");
        if let Some(c) = cursor {
            path.push_str(&format!("&cursor={}", urlencoding::encode(c)));
        }
        if let Some(pr) = pr_url {
            path.push_str(&format!("&prUrl={}", urlencoding::encode(pr)));
        }
        Ok(self.http.get(&path).await?)
    }

    /// GET /v0/agents/{id} — Get agent status.
    pub async fn status(&self, id: &str) -> Result<Agent> {
        Ok(self.http.get(&format!("/v0/agents/{id}")).await?)
    }

    /// GET /v0/agents/{id}/conversation — Get agent conversation logs.
    pub async fn logs(&self, id: &str) -> Result<Conversation> {
        Ok(self.http.get(&format!("/v0/agents/{id}/conversation")).await?)
    }

    /// POST /v0/agents/{id}/stop — Stop a running agent.
    pub async fn stop(&self, id: &str) -> Result<StopResponse> {
        Ok(self.http.post(&format!("/v0/agents/{id}/stop"), &serde_json::Value::Null).await?)
    }

    /// POST /v0/agents/{id}/followup — Add a followup instruction.
    pub async fn followup(&self, id: &str, req: &FollowupRequest) -> Result<FollowupResponse> {
        Ok(self.http.post(&format!("/v0/agents/{id}/followup"), req).await?)
    }

    /// DELETE /v0/agents/{id} — Delete an agent permanently.
    pub async fn delete_agent(&self, id: &str) -> Result<DeleteResponse> {
        Ok(self.http.delete(&format!("/v0/agents/{id}")).await?)
    }

    /// GET /v0/agents/{id}/artifacts — List artifacts generated by an agent.
    pub async fn artifacts(&self, id: &str) -> Result<ArtifactList> {
        Ok(self.http.get(&format!("/v0/agents/{id}/artifacts")).await?)
    }

    /// GET /v0/agents/{id}/artifacts/download?path={path} — Get a presigned download URL.
    pub async fn download_artifact(
        &self,
        id: &str,
        path: &str,
    ) -> Result<GetArtifactResponse> {
        Ok(self
            .http
            .get(&format!(
                "/v0/agents/{id}/artifacts/download?path={}",
                urlencoding::encode(path)
            ))
            .await?)
    }

    /// GET /v0/models — List available models.
    pub async fn models(&self) -> Result<ModelList> {
        Ok(self.http.get("/v0/models").await?)
    }

    /// GET /v0/repositories — List accessible GitHub repositories.
    pub async fn repos(&self) -> Result<RepoList> {
        Ok(self.http.get("/v0/repositories").await?)
    }

    /// GET /v0/me — Get API key information.
    pub async fn me(&self) -> Result<MeResponse> {
        Ok(self.http.get("/v0/me").await?)
    }
}
